### PR TITLE
Review exercise 2

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Review by HengchengZhang — COMMENTED** [review]
Hi @Smit-create, the exercises themselves look good to me, I think we can merge them first and them change with day-04's exercise.

**Comment by HumphreyYang** [comment]
> Hi @Smit-create, the exercises themselves look good to me, I think we can merge them first and them change with day-04's exercise.

I am updating this notebook. I will merge it once I finish it and swap some exercises with day 4.

**Comment by HumphreyYang** [comment]
Hi @Smit-create  and @HengchengZhang,

Please kindly check the updated exercise 1. Please feel free to update if there is anything to be improved.

**Comment by HumphreyYang** [comment]
I think it is better to merge this first and review it in our new PRs after I swap exercises on day 2 and day 4.

I will ping you in the new PR. See you soon : )

**Pull request merged**
