### PR TITLE
Update Exercises for Day 2 and Day 4

### PR DESCRIPTION
**Pull request by HumphreyYang**
Hi @Smit-create, @HengchengZhang, @mmcky, and @shlff,

I have made significant changes in the exercises for Day 2 and Day 4.

For reference, I have left the old solution, and I will remove the output and the old solution once it is good to be merged. It is slightly too late for me to look through it carefully again (and Jupyter notebooks are very hard to maintain), so please kindly join me in reviewing this significant change tomorrow if you are available : )

Many thanks in advance.

### CODE REVIEW

**Comment by shlff** [comment]
Thanks @HumphreyYang . Very nice job. 

As discussed I've modified the exercise set 04 and its solutions, deleted the old solution and added an extra exercise to it.

**Comment by HumphreyYang** [comment]
> Thanks @HumphreyYang . Very nice job.
> 
> As discussed I've modified the exercise set 04 and its solutions, deleted the old solution and added an extra exercise to it.

Many thanks @shlff!

**Comment by HumphreyYang** [comment]
This looks good to me now. I will merge after getting another set of eyes over this PR : ) 

Many thanks everyone for the great work.

**Comment by Smit-create** [comment]
This looks good to me. Thanks, team.

**Pull request merged**
