### PR TITLE
Add exercise1 and solution

### PR DESCRIPTION
**Pull request by HengchengZhang**
Hi @mmcky, this PR adds the modified exercise1 and its solutions.

Additionally I have a few suggestions but I'm not too sure:

1. We are not using the `print()` function to print result, is it good for new learners of Python?
2. Shall we add things like `# TODO: complete ...` in code blocks we want students to add their own code?

### CODE REVIEW

**Comment by mmcky** [comment]
@HengchengZhang I think those would be good additions. 👍

**Comment by mmcky** [comment]
@HengchengZhang I noticed this modifies both `_references/` and the `day01` folder. Are those notebooks the same?

**Comment by HengchengZhang** [comment]
> @HengchengZhang I noticed this modifies both `_references/` and the `day01` folder. Are those notebooks the same?

Yes they are, I will revert the changes in `_references/` to keep it as a reference.

**Comment by HengchengZhang** [comment]
Hi @mmcky, please have a look at the changes.

It should be ready to merge if this look good to you.

**Comment by mmcky** [comment]
@Smit-create I will merge this but if you could take a quick look over it that would be great.

**Review by Smit-create — COMMENTED** [review]
LGTM, Thanks @HengchengZhang and @mmcky

**Pull request merged**
