### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by HengchengZhang**
Hi @mmcky, I made some small touchups to the finished exercises.

Also @shlff I made some changes to day-04 and please have a look whether they look good to you.

### CODE REVIEW

**Comment by HumphreyYang** [comment]
Hi @HengchengZhang,

I did not notice that you have changed the title in this PR : ). Please address the merge conflict when you are available.

Hi @shlff, could you please have a quick review of the changes @HengchengZhang made?

**Comment by shlff** [comment]
Thanks @HengchengZhang and @HumphreyYang  . 

The exercise set 4 looks good to me and is stronger with Hengcheng's modification.

**Comment by HengchengZhang** [comment]
Hi @HumphreyYang, I've fixed the conflicts :D

**Comment by HumphreyYang** [comment]
Many thanks @HengchengZhang, merging.

**Pull request merged**
