### PR TITLE
Update Python basics exercises to day 05

### PR DESCRIPTION
**Pull request by shlff**
Hi @mmcky this PR updates the Python basics exercises on Numpy and Scipy to the day 05 folder. 

Looking forward to your comments.

### CODE REVIEW

**Comment by HumphreyYang** [comment]
Hi @HengchengZhang, 

Could you please merge this exercise set with the exercise on day 5?

Many thanks in advance.

**Comment by HumphreyYang** [comment]
Also, OOP is moved to day 7 now, the exercise on the Python class needs to be moved to day 7 : ) I will do this as well.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

The exercise set is ready. I am merging this now. Many thanks @shlff and @HengchengZhang.

**Comment by shlff** [comment]
Thx for your nice work @HumphreyYang and @HengchengZhang .

**Pull request merged**
