### PR TITLE
remove summer and use Africa

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Comment by Smit-create** [comment]
https://github.com/QuantEcon/workshop.africa-july2023/issues/11#issuecomment-1615580192

**Review by HumphreyYang — APPROVED** [review]

**Comment by HumphreyYang** [comment]
Many thanks @Smit-create!

Hi @mmcky, would you like me and @Smit-create to take charge of merging for now? We will do a cross-check before merging.

**Comment by mmcky** [comment]
@HumphreyYang the workflow I recommend is to go ahead and merge (cc @Smit-create and @HumphreyYang) the exercises as soon as they are ready. 

We can then organise a final review once you think they are ready to go. 

Thanks for your help in pushing this forward.

**Comment by mmcky** [comment]
Another reason for this is `notebooks` are hard to diff and review in github so PR's aren't that effective (other than managing collisions) in this context.

**Comment by HumphreyYang** [comment]
> Another reason for this is `notebooks` are hard to diff and review in github so PR's aren't that effective (other than managing collisions) in this context.

Many thanks @mmcky. The workflow sounds great to me!

**Pull request merged**
