### PR TITLE
add one exercise according to Review exercise 5 #18

### PR DESCRIPTION
**Pull request by chappiewuzefan**
#18

### CODE REVIEW

**Comment by HumphreyYang** [comment]
Many thanks @chappiewuzefan. 

@shlff has kindly agreed to have a quick look into this. Many thanks in advance!

**Comment by shlff** [comment]
Thanks @chappiewuzefan and @HumphreyYang .

Hi @HumphreyYang thanks for the chat. I've added a simple exercise of present values as Exercise 9. 

You may consider shifting it to a front seat.

**Comment by HumphreyYang** [comment]
> Thanks @chappiewuzefan and @HumphreyYang .
> 
> Hi @HumphreyYang thanks for the chat. I've added a simple exercise of present values as Exercise 8.
> 
> You may consider shifting it to a front seat.

Looking great to me! Many thanks @shlff  and @chappiewuzefan.

**Comment by HumphreyYang** [comment]
Hi @chappiewuzefan, 

I will merge this branch with the review branch now.

**Pull request merged**
