### PR TITLE
Added new exercise for Solow-Swan (extended exercise 9)

### PR DESCRIPTION
**Pull request by Smit-create**
cc @mmcky 

@jstac Please have a look once at the new exercise (Just review exercise 4 under the file name exercise_9_new_solution.py)

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @Smit-create. 

I am in favour of merging this when you're happy -- then @jstac can do a bulk review.

**Comment by Smit-create** [comment]
Sure, thanks!

**Comment by mmcky** [comment]
@Smit-create before merging if you can move this to an appropriate `day##` folder that would be great.

**Comment by Smit-create** [comment]
> @Smit-create before merging if you can move this to an appropriate `day##` folder that would be great.

Ahh, sorry. I just merged and saw your comment.

**Pull request merged**
