### PR TITLE
add exercise present values

### PR DESCRIPTION
**Pull request by chappiewuzefan**
add exercise present values

### CODE REVIEW

**Comment by chappiewuzefan** [comment]
@HengchengZhang @HumphreyYang pls have a look ~

**Comment by HumphreyYang** [comment]
Many thanks @chappiewuzefan for the great work!

Could you please group the exercises in the two problem sets into one file (see https://github.com/QuantEcon/workshop.africa-july2023/blob/main/day-04/exercise_set_4.ipynb).

Moreover, please change the file names ending with 5 as it is the fifth day. I will have another look into the content once these changes are made : )

Many thanks in advance.

**Comment by Smit-create** [comment]
Hi @chappiewuzefan, Can you please append your new exercises to the existing one instead of a new file so that it's easy to maintain and upload? Thanks!

Ah, @HumphreyYang mentioned the same. I missed the above comment.

**Comment by chappiewuzefan** [comment]
Hi Team, @Smit-create @HumphreyYang done ~ ready for merge

**Comment by HengchengZhang** [comment]
Many thanks @chappiewuzefan, I would suggest adding some basic frame in the code, e.g.`Market` class to make sure the notebook can be run without errors. Does this sound good to you @HumphreyYang?

**Comment by HumphreyYang** [comment]
> Many thanks @chappiewuzefan, I would suggest adding some basic frame in the code, e.g.`Market` class to make sure the notebook can be run without errors. Does this sound good to you @HumphreyYang?

I will do this now.

**Comment by HumphreyYang** [comment]
Hi @Smit-create and @chappiewuzefan,

Could you please have a final review of the text and code and update the notebook when necessary?

Many thanks in advance.

**Comment by chappiewuzefan** [comment]
> Hi @Smit-create and @chappiewuzefan,
> 
> Could you please have a final review of the text and code and update the notebook when necessary?
> 
> Many thanks in advance.

Great work @HumphreyYang  reviewed, look great to me~

**Comment by Smit-create** [comment]
Let's merge this and we will fix it if there are any issues. Thanks, @HumphreyYang!

**Pull request merged**
